### ISSUE TITLE
Missing CSS3 Selector in IE6 and IE7 

### ISSUE THREAD

**Issue by spy23** [bialecki/yui3-gallery#1]
If you use the lightbox as described on the example page or if you try to run your own lightbox it will fail in internet explorer 6 and 7. 

this is because of the default lightbox selector string "a[rel^=lightbox]" that uses css3 selector syntax. this syntax is not supportet by ie6 and ie7. in the example yui only loads node, but node does not include css3 selectors by default. 

Note: CSS3 selector support is not included by default with Node, you will need to include the "selector-css3" module for CSS3 support. 

if you add the css3-selector dependency to the modul the lightbox will even work fine in ie6 and ie7:

YUI({
    modules: {
        'gallery-lightbox': {
            fullpath: 'js/gallery-lightbox.js',
            requires: ['base','node','anim', "selector-css3"]
      }
    }
}).use('gallery-lightbox', function(Y) {
    Y.Lightbox.init();
});

regards,
stefan

**Comment by bialecki** [comment]
Thanks for the fix, I'll add this in.

**Comment by bialecki** [comment]
Committed fix.
