### ISSUE TITLE
Selector will pick up unrelated links in IE7

### ISSUE THREAD

**Issue by tivac** [bialecki/yui3-gallery#2]
http://tivac.com/yui3/gallery-lightbox/

Click on the "I'm unrelated!" link and watch as the lightbox tries to open a link that shouldn't be lightboxed.

I was able to fix this issue by adding "css3-selectors" as a required YUI3 module to a local copy. See http://tivac.com/yui3/gallery-lightbox/modified.htm

The lightbox can't find the other related images in IE7 either, but that's a separate bug I'm still tracking down.

**Comment by tivac** [comment]
I'm a moron, this is a dupe.

**Comment by bialecki** [comment]
No problem :) Cool if I close this one?

**Comment by bialecki** [comment]
Nm, obviously already closed.
