### ISSUE TITLE
Lightbox doesn't work in IE6/7

### ISSUE THREAD

**Issue by tivac** [bialecki/yui3-gallery#3]
Not actually your fault, it's a bug in YUI 3. Wanted you to be aware though.

http://yuilibrary.com/projects/yui3/ticket/2528799

I can't think of a simple fix at the moment that isn't a massive kludge, ugh.

**Comment by bialecki** [comment]
Interesting, I'll look into this one.  Might have to work outside of YUI selector engine.  Let me look.

**Comment by tivac** [comment]
I made the following modification to get this to work. I'm not wild about the change as it's definitely a hack but it'll do until the bug is fixed.

http://gist.github.com/373157 - line 380ish or so

**Comment by tivac** [comment]
:skull:
